services:
  postgres:
    image: postgres:15
    container_name: go-postgres
    #restart: always
    env_file:
      - postgres.env
    ports:
      - "5434:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U devuser" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  go-examples:

